services:
  runner:
    build:
      context: .
      dockerfile: runner/Dockerfile
      target: runner
    env_file:
      - .env

    # TODO: split permission scope
    privileged: true
    cgroup: "host"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # for testing
    ports:
      - 3000:3000
