services:
  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    init: true
    command: sleep infinity
    env_file:
      - .env

    # TODO: split permission scope
    privileged: true
    cgroup: "host"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
