services:
  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    init: true
    command: sleep infinity

    # TODO: split permission scope
    privileged: true
    cgroup: "host"
