[package]
name = "runner"
edition.workspace = true
version.workspace = true
repository.workspace = true

[dependencies]
runner-schema.workspace = true

thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
