[package]
name = "runner-schema"
edition.workspace = true
version.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
more-convert.workspace = true

[lints]
workspace = true
